# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$python$username$hostname$directory$aws$git_branch$character'

add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[line_break]
disabled = true

[git_branch]
symbol = " "

[python]
format = "[(\\($virtualenv\\) )]($style)"

[aws]
symbol = "󰅟 "
